name: roboshop-shipping-cicd
on:
  push:
  workflow_dispatch:
jobs:
  common:
    uses: linga-devsecops-actions/14.20.github-actions-roboshop-reusable-workflows/.github/workflows/shipping-ci-cd.yaml@main
    with:
      project: roboshop
      component: shipping
      environment: dev
      app_type: java
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
